server:
  port: 9090

spring:
  profiles:
    include: oauth, mysql

  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false
  thymeleaf:
    cache: false

  jpa:
    show-sql: true #if true, Show DB processing
    hibernate:
      ddl-auto: update  #DDL

