server:
  port: 9090

spring:
  devtools:
    livereload:
      enabled: true
  freemarker:
    cache: false
  thymeleaf:
    cache: false

  #DB setting
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/yoongyum?autoReconnect=true
    username: root
    password: 1234

  jpa:
    show-sql: true #true ??? JPA ??? ?? ??
    hibernate:
      ddl-auto: update  #DDL ??? DB? ?? ?? ?? ??

